baseURL = "https://yuqingc.github.io/"
languageCode = "en-us"
pygmentsCodeFences=true
theme = "Mainroad"
paginate = "10" # Number of posts per page
summaryLength = 50
hasCJKLanguage = true # To make summary displays correctly
publishDir = "public" # Incase the default public dir change
DefaultContentLanguage = "zh-cn"

# Language configs
[languages]
  [languages.zh-cn]
    title = "é»‘äººdeé—®å·ğŸŒšâ“"
    contentDir = "content/zh-cn"
    languageName = "ç®€ä½“ä¸­æ–‡"
    weight = 1

    [languages.zh-cn.Params]
      subtitle = "" # Subtitle of your site. Used in site header

    [languages.zh-cn.Params.logo]
      image = "images/avatar.png" # Logo image. Path relative to "static"
      title = "é»‘äººdeé—®å·ğŸŒšâ“" # Logo title, otherwise will use site title
      subtitle = "æ— äº§é˜¶çº§å·¥äºº/Coder ğŸ”¨" # Logo subtitle

    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        identifier = "source-cn"
        name = "ç¼–è¾‘"
        url = "https://github.com/yuqingc/yuqingc.github.io"
        weight = 103

      [[languages.zh-cn.menu.main]]
        identifier = "issues-cn"
        name = "åé¦ˆ"
        url = "https://github.com/yuqingc/yuqingc.github.io/issues"
        weight = 104

      [[languages.zh-cn.menu.main]]
        identifier = "goen"
        name = "English"
        url = "/en"
        weight = 105

    [languages.zh-cn.Author] # Used in authorbox
      name = "é»‘äººdeé—®å·ğŸŒšâ“"
      bio = "é›¨ä¸‹æ•´å¤œ..."
      avatar = "images/avatar.png"

  # English Lang Configs
  [languages.en]
    title = "Matt's Home"
    contentDir = "content/en"
    languageName = "English"
    weight = 2

    [languages.en.Params]
      subtitle = "Coder ğŸ”¨" # Subtitle of your site. Used in site header

    [languages.en.Params.logo]
      image = "images/avatar.png" # Logo image. Path relative to "static"
      title = "Matt's Home" # Logo title, otherwise will use site title
      subtitle = "I might be coding right now... ğŸ”¨" # Logo subtitle

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "source-en"
        name = "Edit This Page"
        url = "https://github.com/yuqingc/yuqingc.github.io"
        weight = 103

      [[languages.en.menu.main]]
        identifier = "issues-en"
        name = "Feedback"
        url = "https://github.com/yuqingc/yuqingc.github.io/issues"
        weight = 104

      [[languages.en.menu.main]]
        identifier = "gocn"
        name = "ç®€ä½“ä¸­æ–‡"
        url = "/zh-cn"
        weight = 105

    [languages.en.Author] # Used in authorbox
      name = "Matt"
      bio = "Why you always in a mood?"
      avatar = "images/avatar.png"

############################# NON-LANG CONFIGS ##################################

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # enable html in markdown files

[Params]
  description = "John Doe's Personal blog about everything" # Site description. Used in meta description
  copyright = "yuqingc" # copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["posts"] # specify section pages to show on home page and the "Recent articles" widget
  #dateformat = "2006-01-02" # change the format of dates
  #mathjax = true # Enable MathJax
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "#1E88E5" # Override highlight color #e22d30
  customCSS = ["css/custom.css"] # Include custom CSS files

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["ddg-search", "recent", "taglist", "categories", "social"]

[Params.widgets]
  recent_num = 10 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  # facebook = "username"
  # twitter = "username"
  # instagram = "username"
  # linkedin = "username"
  # telegram = "username"
  github = "yuqingc"
  # gitlab = "username"
  # bitbucket = "username"
  email = "mr.chenyuqing@live.com"

[[Params.widgets.social.custom]]
  title = "(ã‚œ-ã‚œ)ã¤ãƒ­ å¹²æ¯~"
  url = "https://space.bilibili.com/76849204"
  icon = "bilibili.svg"
